version: '3.4'

services:
  bricssocial.api:
    build:
      context: .
      dockerfile: src/BricsSocial.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - S3_SERVICE_URL=https://s3.yandexcloud.net
      - S3_BUCKET_NAME=brics
      - S3_REGION=us-east-1
      - S3_KEY_ID=YCAJET44SkrCbm3FFq0mno2At
      - S3_KEY_SECRET=YCPvapadbeubpF8lF0-03QwylMLE7p95K_iDGjM8
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro