version: '3.4'

services:
  postgres:
    image: postgres:14.2-alpine
    container_name: brics-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bricsdb
    volumes:
      - postgres:/var/lib/postgresql/data
    #networks:
    #  - postgres

  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    restart: always
    ports:
      - 5050:80
    environment:
     - PGADMIN_DEFAULT_EMAIL=admin@brics.org
     - PGADMIN_DEFAULT_PASSWORD=Admin123!
    volumes:
      - /data/pgadmin:/root/.pgadmin
    #networks:
    #  - postgres

  bricssocial.api:
    image: ${DOCKER_REGISTRY-}bricssocialapi
    environment:
      - BricsConnectionString=Username=postgres;Password=postgres;Host=postgres;Port=5432;Database=bricsdb
    #networks:
    #  - postgres

volumes:
  postgres:
    name: brics-db

#networks:
#  postgres:
#    driver: bridge